//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ev3Solucoes.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Eventos
    {
        public int IdEvento { get; set; }
        public string nomeEvento { get; set; }
        public System.DateTime dataEvento { get; set; }
        public string localEvento { get; set; }
    }
}
